export * from './Banner';
export * from './ServicesRow'
export * from './NotificationsCard';
export * from './SolvenciaCard';
export * from './ExpedientesCard';
export * from './SumateHome';
export * from './SumateAntecedentes';
export * from './SumateInfo';
export * from './SumateInst';
export * from './SumateUni';
export * from './SumateHow';
export * from './SumateConoce';
export * from './FullPageSnap';